.INCLUDE "m328Pdef.inc"

.EQU LED0 = PB0
.EQU LED1 = PB1
.EQU LED2 = PB2
.EQU LED3 = PB3
.EQU LED4 = PB4

START:
	SBI DDRB, LED0
	SBI	DDRB, LED1
	SBI DDRB, LED2
	SBI DDRB, LED3
	SBI DDRB, LED4

MAIN:
	RCALL DELAY
    INC R18
    CPI R18, 32
    BREQ CLEAR
    RETURN:
        IN R16, PORTB
        LDI R17, 0xE0
        AND R17, R16
        OR  R17, R18
        OUT PORTB, R17
		RJMP MAIN

CLEAR:
    LDI R18, 0
    RJMP RETURN

DELAY:
    LDI R16, 83
    DELAY_LOOP:
        DEC R0
        RJMP DELAY_LOOP
        DEC R1
        RJMP DELAY_LOOP
    RET
